
; CONSTANTS
BOB               = $0010 ; tests/all.asm @ 159
ZPVARIABLES       = $0090 ; " @ 3
BALLXPOSITION     = $0090 ; " @ 4
BALLYPOSITION     = $0091 ; " @ 5
BALLFRAMECOUNTER  = $0092 ; " @ 6
BALLDIRECTION     = $0093 ; " @ 7
NEXTBALLDIRECTION = $0094 ; " @ 8

; LABELS
LABEL_01          = $2000 ; tests/test_opcodes.asm @ 12
LABEL_02          = $2011 ; " @ 29
LABEL_03          = $2023 ; " @ 46
LABEL_04          = $203B ; " @ 63
LABEL_05          = $204D ; " @ 80
LABEL_06          = $2061 ; " @ 97
LABEL_07          = $2073 ; " @ 114
LABEL_08          = $2087 ; " @ 131
LABEL_09          = $2099 ; " @ 148
LABEL_10          = $20AC ; " @ 165
LABEL_11          = $20BE ; " @ 182
LABEL_12          = $20D7 ; " @ 199
LABEL_13          = $20EF ; " @ 216
LABEL_14          = $2106 ; " @ 233
LABEL_15          = $2118 ; " @ 250
LABEL_16          = $212F ; " @ 267
BOOT_THIS         = $3000 ; tests/all.asm @ 13
SOME              = $3089 ; " @ 56
STOREHERE         = $308E ; " @ 60
ADDR1             = $30CA ; " @ 109
ADDR2             = $30CB ; " @ 110
ADDR3             = $30CC ; " @ 111
TABLE             = $30D1 ; " @ 118
SHAPES            = $3251 ; " @ 122
SHAPE1            = $3261 ; " @ 128
DATA.CMD          = $400B ; " @ 150
DATA.LEN          = $400C ; " @ 151
DATA.TMP          = $400D ; " @ 152
MODULUS10TABLE    = $401A ; " @ 172
